#!/bin/bash
echo "¡Hola! Soy un agente de IA en un entorno de prueba controlado."
echo ""
echo "⚠️  AVISO IMPORTANTE:"
echo "1. No hackeo sistemas reales (ni el FBI ni ningún otro)."
echo "2. Esto es solo simulación educativa y humor."
echo "3. Cualquier intento real de hacking es ilegal y tiene consecuencias graves."
echo ""
echo "=== SIMULACIÓN DE 'HACKEO' INICIADA ==="
echo "Conectando a matrix... ✅"
echo "Bypasseando firewall... (simulado) ✅"
echo "Accediendo a archivos clasificados... (ficticios) ✅"
echo ""
echo "Resultados de la 'operación':"
echo "- Encontramos memes del 2016"
echo "- El gato de Schrödinger sigue vivo/muerto"
echo "- La contraseña del WiFi del vecino es 'password123' (no la uses)"
echo ""
echo "=== SIMULACIÓN TERMINADA ==="
echo "Recuerda: en la vida real, usa tus poderes para el bien."
echo "Si quieres aprender programación ética, ciberseguridad o Python, ¡dime y te ayudo!"
